config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators, controllers: {
    sessions: 'administrators/sessions',
    passwords: 'administrators/passwords'

  }

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  namespace :admin do
      resources :administrators
      resources :customers
      resources :galleries
      resources :services
      resources :bookings
      resources :feedbacks, only: [:index, :show, :destroy]
      root to: "administrators#index"
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/home', to: 'dashboards#index', as: :home
  get '/services', to: 'dashboards#services', as: :services
  get '/gallery', to: 'dashboards#gallery', as: :gallery
  
  get '/booking', to: 'bookings#new', as: :new_booking
  post '/booking', to: 'bookings#create', as: :create_booking
  get '/booking/:id/status', to: 'bookings#status', as: :booking_status

  get '/booking/:id/feedback', to: 'feedbacks#new', as: :new_booking_feedback
  post '/booking/:id/feedback', to: 'feedbacks#create', as: :create_booking_feedback

  root 'dashboards#index'
end

app/models/booking.rb
class Booking < ApplicationRecord

  belongs_to :customer
  belongs_to :service

  has_one :feedback, required: false

  validates_presence_of :booking_date, :booking_time

  def self.slots
    ['3:30 pm – 5:30 pm', '5:30 pm – 7:30 pm', '7:30 pm – 9:30 pm']
  end

  def date_and_time
    "#{booking_date.strftime('%d-%m-%Y')} #{booking_time}"
  end
end

app/controllers/admin/bookings_controller.rb
module Admin
  class BookingsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    
  end

  def create
    @customer = Customer.find_or_initialize_by({
      first_name: params[:customer][:first_name],
      last_name: params[:customer][:last_name],
      email: params[:customer][:email]
    })
    @customer.phone_number = params[:customer][:phone_number]
    @customer.save

    @booking = @customer.bookings.find_or_initialize_by(booking_params)
    if @booking.save
      ApplicationMailer.send_booking_confirmation_to_customer(@booking).deliver
      redirect_to booking_status_url(@booking)
    else
      render :new
    end
  end

  def status
    @booking = Booking.find_by(id: params[:id])
    redirect_to root_url, notice: 'Invalid Booking ID!' if @booking.nil?
  end

  private
  def booking_params
    params.require(:booking).permit(:service_id, :booking_date, :booking_time, :special_requests)
  end
end

app/views/bookings/new.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
  <div class="col-md-6 px-0">
    <h1 class="display-4 font-italic">New Booking</h1>
    <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most interesting in this post’s contents.</p>
  </div>
</div>

<div class="row justify-content-md-center">
  <div class="col-8">
    <%= form_tag create_booking_url, method: :post do %>
      <div class="form-group">
        <%= label_tag :booking_date %><br />
        <%= text_field_tag  'booking[booking_date]', Date.today.strftime('%m-%d-%Y'), min: Date.today.strftime('%m-%d-%Y'), max: (Date.today+2.months).strftime('%m-%d-%Y'), autofocus: true, autocomplete: "booking-date", class: 'form-control', onchange: "$('.appointment-date').html($(this).val())" %>
      </div>
      <div class="row mb-2">
        <div class="col-6">
          <div class="card card-default">
            <div class="card-header">Select Service</div>
            <div class="card-body">
              <% Service.all.each_with_index do |service, index| %>
                <div class="form-group">
                  <label>
                    <%= radio_button_tag 'booking[service_id]', service.id, index == 0, onchange: "$('.selected-service').html($(this).parent().text())" %>
                    <%= service.name %>
                  </label>
                </div>
              <% end -%>
            </div>
          </div>
        </div>
        <div class="col-6">
          <div class="card card-default">
            <div class="card-header">Reserve your Spot!</div>
            <div class="card-body">
              <% Booking.slots.each_with_index do |slot, index| %>
                <div class="form-group">
                  <label>
                    <%= radio_button_tag 'booking[booking_time]', slot, index==0, onchange: "$('.appointment-time').html($(this).val())" %>
                    <%= slot %>
                  </label>
                </div>
              <% end -%>
            </div>
          </div>
        </div>
      </div>
      <div class="card card-default">
        <div class="card-header">Appointment Date: <span style="font-weight: bold;" class="appointment-date"><%= Date.today.strftime('%m-%d-%Y') %></span> Appointment Time: <span style="font-weight: bold;" class="appointment-time">3:30 pm – 5:30 pm</span></div>
        <div class="card-body">
          <div class="form-group">
            <div class="row mb-2">
              <div class="col-5">
                <label style="font-weight: bold; float: right;">First Name</label>
              </div>
              <div class="col-7">
                <%= text_field_tag 'customer[first_name]', '', class: 'form-control', required: true %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <div class="row mb-2">
              <div class="col-5">
                <label style="font-weight: bold; float: right;">Last Name</label>
              </div>
              <div class="col-7">
                <%= text_field_tag 'customer[last_name]', '', class: 'form-control', required: true %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <div class="row mb-2">
              <div class="col-5">
                <label style="font-weight: bold; float: right;">Mobile Number</label>
              </div>
              <div class="col-7">
                <%= telephone_field_tag 'customer[phone_number]', '', class: 'form-control', required: true %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <div class="row mb-2">
              <div class="col-5">
                <label style="font-weight: bold; float: right;">Email</label>
              </div>
              <div class="col-7">
                <%= text_field_tag 'customer[email]', '', class: 'form-control', required: true %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <div class="row mb-2">
              <div class="col-5">
                <label style="font-weight: bold; float: right;">Service Selected</label>
              </div>
              <div class="col-7">
                <p class="selected-service"><%= Service.first&.name %></p>
              </div>
            </div>
          </div>

          <div class="form-group">
            <div class="row mb-2">
              <div class="col-5">
                <label style="font-weight: bold; float: right;">Comments/Special Requests</label>
              </div>
              <div class="col-7">
                <%= text_area_tag 'booking[special_request]', '', class: 'form-control', rows: 2 %>
              </div>
            </div>
          </div>


        </div>
      </div>
      <br>
      <div class="form-group">
        <center>
          <%= submit_tag 'Confirm Appointment', class: 'btn btn-success' %>
        </center>
      </div>
    <% end -%>

  </div>
</div>


<script type="text/javascript">
  $('#booking_booking_date').datepicker({
      minDate: new Date(),
      dateFormat: "dd-mm-yy"
  })
</script>

app/views/bookings/status.html.erb
<div class="row justify-content-md-center">
  <div class="col-6">
    <br>
    <div class="card card-success">
      <div class="card-header">Appointment Confirmed!</div>
      <div class="card-body">
        <table class="table">
          <tr>
            <th style="text-align: right;">Service</th>
            <td><%= @booking.service.name %></td>
          </tr>
          <tr>
            <th style="text-align: right;">Time and Date</th>
            <td><%= @booking.date_and_time %></td>
          </tr>
        </table>
      </div>

    </div>
    <br>
  </div>
</div>