config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators, controllers: {
    sessions: 'administrators/sessions',
    passwords: 'administrators/passwords'

  }

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  namespace :admin do
      resources :administrators
      resources :customers
      resources :galleries
      resources :services
      resources :bookings
      resources :feedbacks, only: [:index, :show, :destroy]
      root to: "administrators#index"
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/home', to: 'dashboards#index', as: :home
  get '/services', to: 'dashboards#services', as: :services
  get '/gallery', to: 'dashboards#gallery', as: :gallery
  
  get '/booking', to: 'bookings#new', as: :new_booking
  post '/booking', to: 'bookings#create', as: :create_booking
  get '/booking/:id/status', to: 'bookings#status', as: :booking_status

  get '/booking/:id/feedback', to: 'feedbacks#new', as: :new_booking_feedback
  post '/booking/:id/feedback', to: 'feedbacks#create', as: :create_booking_feedback

  root 'dashboards#index'
end

app/models/feedback.rb
class Feedback < ApplicationRecord

  belongs_to :booking
  validates_presence_of :content
end

app/controllers/admin/feedbacks_controller.rb
module Admin
  class FeedbacksController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_booking
  before_action :check_if_feedback_already_provided

  def new
  end

  def create
    @feedback = Feedback.new(feedback_params)
    if @feedback.save
      redirect_to root_url, notice: 'Feedback for the booking has been submitted successfully'
    else
      render :new
    end
  end

  private

  def feedback_params
    params.require(:feedback).permit(:content, :booking_id)
  end

  def check_if_feedback_already_provided
    redirect_to root_url, notice: 'Feedback for the booking has already been submitted' if @booking.feedback.present?
  end

  def set_booking
    @booking = Booking.find_by(id: params[:id])
    redirect_to root_url, notice: 'Invalid Booking ID!' if @booking.nil?
  end
end

app/views/feedbacks/new.html.erb
<div class="row justify-content-md-center">
  <div class="col-6">
    <br>
    <div class="card card-default">
      <div class="card-header">Leave a Feedback</div>
      <div class="card-body">
        <%= form_tag(create_booking_feedback_url(@booking)) do %>
          <p>Please provide feedback for your booking at <b><%= @booking.date_and_time %></b> for service: <b><%= @booking.service.name %></b></p>
          <div class="form-group">
            <%= label_tag :feedback %><br />
            <%= text_area_tag 'feedback[content]', '', autocomplete: "content", class: 'form-control', rows: 2, required: true %>
          </div>

          <%= hidden_field_tag 'feedback[booking_id]', @booking.id %>

          <div class="form-group">
            <%= submit_tag "Leave a Feedback", class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
    <br>
  </div>
</div>