config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators, controllers: {
    sessions: 'administrators/sessions',
    passwords: 'administrators/passwords'

  }

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  namespace :admin do
      resources :administrators
      resources :customers
      resources :galleries
      resources :services
      resources :bookings
      resources :feedbacks, only: [:index, :show, :destroy]
      root to: "administrators#index"
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/home', to: 'dashboards#index', as: :home
  get '/services', to: 'dashboards#services', as: :services
  get '/gallery', to: 'dashboards#gallery', as: :gallery
  
  get '/booking', to: 'bookings#new', as: :new_booking
  post '/booking', to: 'bookings#create', as: :create_booking
  get '/booking/:id/status', to: 'bookings#status', as: :booking_status

  get '/booking/:id/feedback', to: 'feedbacks#new', as: :new_booking_feedback
  post '/booking/:id/feedback', to: 'feedbacks#create', as: :create_booking_feedback

  root 'dashboards#index'
end

app/views/layouts/_footer.html.erb
<footer class="blog-footer">
  <p><a href="/">MB Beauty Parlor</a>.</p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header class="blog-header py-3">
  <div class="row flex-nowrap justify-content-between align-items-center">
    <div class="col-12 text-center">
      <a class="blog-header-logo text-dark" href="/">MB Beauty Parlor</a>
    </div>
  </div>
</header>

<div class="nav-scroller py-1 mb-2">
  <nav class="nav d-flex justify-content-center">
    <%= link_to "Home", '/', class: "p-2 text-muted #{'active' if params[:action] == 'index'}" %>
    <%= link_to "Services", services_url, class: "p-2 text-muted #{'active' if params[:action] == 'services'}" %>
    <%= link_to "Gallery", gallery_url, class: "p-2 text-muted #{'active' if params[:action] == 'gallery'}" %>
    <%= link_to "Booking", '/booking', class: "p-2 text-muted #{'active' if params[:controller] == 'bookings'}" %>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MbParlor2019</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all' %>
    
    <%= javascript_include_tag 'application' %>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>


  <body data-gr-c-s-loaded="true" cz-shortcut-listen="true">
    <%= render partial: 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render partial: 'layouts/footer' %>

  </body>
</html>

<% if notice || alert %>
  <div class="modal fade" id='alertModal' tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-body"><h3><%= notice || alert %></h3></div>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    $(document).ready(function(){
      $('#alertModal').modal('show')
    })
  </script>
<% end -%>